### ISSUE TITLE
show the scope in a view rather than console.

### ISSUE THREAD

**Issue by ctf0** [facelessuser/ScopeHunter#11]
is there away to output the scopes to a view instead of console ,and the view gets updated each time the scope changes ,this way we can move the view to anywhere and we dont have to keep draging the console up and down to find the rest of the scopes + it helps with the small screens.

maybe something like how this work
https://packagecontrol.io/packages/sublime-text-2-buildview

**Comment by facelessuser** [comment]
Do you mean like with this?

```js
    // Show scope in auto-popup panel
    "show_panel": true,
```

This will open up a special panel.

You can configure it anyway you like, just look in the settings file.

**Comment by facelessuser** [comment]
Okay, I read your question a bit more, and you are specifically looking to have it put in a normal view.  That doesn't exist yet, but if I get some time, I could probably do that.

**Comment by ctf0** [comment]
sweet ,thanx.

**Comment by facelessuser** [comment]
@ctf0 recently I have been adding tooltip functionality for ST3 3071+, are views still a priority for you?  I don't want to waste time on the view feature if in all honesty the new tooltip feature is what you may be using moving forward.  Tooltip is still in development and has some bugs, but you can try it out now.  I plan on making tooltips the default when the new public beta releases.

![Tooltip](https://dl.dropboxusercontent.com/u/342698/ScopeHunter/tooltip-copy.png)

Let me know what you think.  If tooltips is the way you want to go, then I will probably ditch the view feature.

**Comment by ctf0** [comment]
WHAAAAAAAAAAAAAAAAAAAAAT ,is this the new tooltip feature in ST ?, +1000 to the new implementation.

**Comment by facelessuser** [comment]
Cool, I have a new release coming later today which should fix the remaining bugs.  I will close this issue as I expect the tooltip to be the most used method moving forward making things like view, or even panels obsolete.
