### ISSUE TITLE
Display the actual matching selector (not just the name)

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ScopeHunter#12]
Current behavior:
```
foreground selector:           Function (definition)
```

Suggested behavior:
```
foreground selector:           Function (definition) <entity.name.function>
```

This also solves use cases where the name is not set.

---

In a similar regard, I'd prefer if the implicit `foreground` and `background` matches from the general settings were highlighted a bit differently so it's easier to see.

And finally, what does "simulated trans" mean? Since it always shows the same as the "normal" color I'd suggest to add an option for hiding it.

**Comment by facelessuser** [comment]
I still take a look and see what I can do.

>And finally, what does "simulated trans" mean? Since it always shows the same as the "normal" color I'd suggest to add an option for hiding it.

Not always :smile:.  Some themes will use a transparent color.  This of course shows a color that mixes the color behind it with itself giving you the color you actually see.  Though, I will probably make it am optional setting.  I did this because was thinking about showing the color in the tooltip, I am not sure yet how limited CSS support is yet.

**Comment by FichteFoll** [comment]
Ah, I see. That makes sense and is a nice addition, but it should only be displayed when it's actually different from the original (=transparency is used) since it's rather rare from my experience.

**Comment by facelessuser** [comment]
That's a good idea.

**Comment by facelessuser** [comment]
Okay, simulated transparency actually wasn't working right, but it is working now, and it will only show up when there is something important to show. https://github.com/facelessuser/ScopeHunter/commit/c85832131f5abd602d5fc8a458dc8ec5db353860.

So, one down. One to go.

**Comment by facelessuser** [comment]
Finished adding this in commit https://github.com/facelessuser/ScopeHunter/commit/6b3271960ddcb747e5bc9ae19d93958f28777eb1.

**Comment by FichteFoll** [comment]
:+1:
