### ISSUE TITLE
Use color in popup

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ScopeHunter#13]
Since the popup supports foreground and background color customization, how about painting the color rgb hashes in their respective color (and adjusting text color to be readable)? Or alternatively adding a div behind it to just show the color.

**Comment by facelessuser** [comment]
Good idea.  Actually thought about this, but didn't bother implementing it before the initial push.  Just wanted to get something out people could play with.

**Comment by FichteFoll** [comment]
Sure, I figured this was already on your radar but having a dedicated issue for it sure won't hurt.

**Comment by facelessuser** [comment]
Definitely, thanks.

**Comment by facelessuser** [comment]
Sadly, CSS is so limited in tooltips that the div option just doesn't work.  I will probably just paint their background and adjust the text based on lumens.

**Comment by facelessuser** [comment]
Bah, can't even color a background of an inline tag.  Jon apparently only added `background-color` for block elements.  This isn't currently going to be workable unless Jon makes CSS and HTML support for feature rich.

**Comment by FichteFoll** [comment]
It does indeed look a bit weird like this (which is also the only way it works):

```py
        popup_text = """\
            A div with color #123456
            <div style="margin: 0 0 0 9.2em; background-color: #123456; color: #123456">#123456</div>
        """
        self.view.show_popup(popup_text)


```

since background-color is only supported on block elements (that are `display: block`, meaning no override possible) it will have to be on a new line currently.

**Comment by facelessuser** [comment]
Yeah its just enough support to make you frustrated that more support isn't there.  I will see if I can come up with something that doesn't make me too angry.

I really do hope Jon adds in some more support in the future.  Current support is just so crippled that it really limits the tooltips.

**Comment by facelessuser** [comment]
I think I got something figured out for this, so this should be in the final in the next release.

```python
def color_box(color, caption):
    rgba = RGBA(color)
    display_color = rgba.get_rgb()
    display_text = rgba.get_rgba().upper()
    font_color = '#FFFFFF' if rgba.luminance() <= 127 else '#000000'
    return '<div class="color-box-frame"><div class="color-box" style="background-color: %s; color: %s">%s</div></div><span>%s</span>' % (display_color, font_color, display_text, caption) 
```

```css
.color-box-frame {
    margin: 10px 0 0 0;
    background-color: #CCCCCC;
}

.color-box {
    margin: 1px;
}
```

This will provide a small 1px frame around the color box, and the box will be filled with the color and have the hex value inside it.  Underneath it will be the caption letting you now whether it is a foreground or background etc.

**Comment by FichteFoll** [comment]
good idea

**Comment by facelessuser** [comment]
Turned out not too bad.

![screenshot - 2_19_2015 12_16_09 pm](https://cloud.githubusercontent.com/assets/1055125/6273996/299e412c-b831-11e4-91ec-fc5447cfeb5a.png)

**Comment by facelessuser** [comment]
Resolved in new commit https://github.com/facelessuser/ScopeHunter/commit/0bd54ca8e860a8f839badcbae30fea0fdb0f5843.

**Comment by FichteFoll** [comment]
That's not too bad indeed. By the way, think it makes sense to "show" the alpha strength in the background hash?

**Comment by facelessuser** [comment]
What do you mean?  Like, show the simulated background color below in the **true** background box?  If so, I've thought about it; I've just been undecided on that and haven't pulled the trigger on it..

**Comment by FichteFoll** [comment]
Never mind, I'm blind.
