### ISSUE TITLE
Scheme not opened correctly on Windows

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ScopeHunter#14]
When clicking the scheme on the popup, the following file is opened:
`/C/Users/Fichte/AppData/Roaming/Sublime Text 3/Packages/Packages\Theme - Nil\Tubnil_mod.tmTheme`

I think you can see where this goes wrong, but to clarify: ColorSchemeMatcher adjusts its internal path to use the correct os.path.sep but when fetching the scheme as the popup text gets constructed (and the on_navigate targets are established) this is not considered.
Imo, the correct action here would be to not "correct" forwards slashes to backslashes in ColorSchemeMatcher.

**Comment by facelessuser** [comment]
I was afraid I was going to do something lame like this without testing on windows :smile:.

**Comment by facelessuser** [comment]
Fixed in commit https://github.com/facelessuser/ScopeHunter/commit/363a4bb14a093dddedddb857c99985924a95efbb.
