### ISSUE TITLE
Auto-detect light or dark css

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ScopeHunter#16]
Since you are inspecting the schemes anyway it would be a piece of a cake to auto-detect whether the user would prefer the dark or the light style for the popup. I suggest to use the setting "auto" for that and make it the default.

**Comment by facelessuser** [comment]
Hmm.  I was actually considering something like this as I use a light theme in the morning and dark at night.  I will probably make the dark and light CSS configurable so people can match their themes.

**Comment by FichteFoll** [comment]
They actually are already, just overriding the file with the "usual method" will make the overridden file get picked up.

**Comment by facelessuser** [comment]
True.  But, I will also make it configurable in the settings file for the novices.

**Comment by facelessuser** [comment]
In commit https://github.com/facelessuser/ScopeHunter/commit/b8ca5dcab2bf4e2dee7b383d90ae694b50a3eba1.

There won't be a new release until I address other issues.
