### ISSUE TITLE
Highlight more than just one scope extend

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ScopeHunter#19]
Following up on #15 I got the idea to mirror the scope highlighting that http://tmtheme-editor.herokuapp.com/ does:

![2015-02-22_22 57 53](https://cloud.githubusercontent.com/assets/931051/6320734/564a4c5e-bae6-11e4-8d3d-f6466fe060ca.png)
(hovering the string)

Different colors could be chosen by a configurable list of scope names that includes the defaults like `variable`, `constant` etc. or could just inspect the active color schemes for all available colors and choose some that are different enough up the first or second neighbour, if you know what I mean. They can also repeat easily enough.

The only issue is that I'm not sure how the regions from add_regions are layered and if order of the API calls affects them, especially regarding underline mode.

Might want to suggest an API method to extract a certain scope (level) of a point based on a second parameter over at the issues repo which would be more efficient.

**Comment by facelessuser** [comment]
Region stuff is a bit of a mess with overlaying.  It's a neat idea, but I will have to weigh the usefulness against the effort to add something like this. The good thing about scopehunter in instant mode, is you can just move your cursor left or right and see the scope change.  You quickly get the gist of range etc.

**Comment by FichteFoll** [comment]
Sure thing, I prolly wouldn't really use it either since I generally prefer to work on the syntax definitions directly, but it's the thought that I wanted to write down.

**Comment by facelessuser** [comment]
I've formally decided to close this as I don't think I will be looking into this any further.
