### ISSUE TITLE
Evaluating theme failed

### ISSUE THREAD

**Issue by leesei** [facelessuser/ScopeHunter#20]
I encountered this error when I enabled `show_popup`.
The background is my user setting.

![selection_001](https://cloud.githubusercontent.com/assets/544400/7605127/9b499ebe-f97e-11e4-93d3-63b517981365.png)

**Comment by facelessuser** [comment]
Can you post your theme?

**Comment by leesei** [comment]
I'm using [MattDMo/Neon-color-scheme](https://github.com/MattDMo/Neon-color-scheme).

https://raw.githubusercontent.com/MattDMo/Neon-color-scheme/master/Neon.tmTheme

**Comment by facelessuser** [comment]
I will give it try either tonight or tomorrow and see if there is something I am missing.

**Comment by leesei** [comment]
Thanks a lot.

**Comment by facelessuser** [comment]
Please let me know if you see any errors in the console.  I just pulled down the Neon theme and used scope hunter with no issues.

Also, my JSON files with neon look different than yours in the picture.  Are you using a different package for JSON languages?

Also, are you sure you are using the latest Neon theme and latest ScopeHunter?  I am using the very latest of both without issues.

**Comment by leesei** [comment]
Oops, I restarted my Sublime today and it works fine.
Sorry for the mis-report.

**Comment by facelessuser** [comment]
Not a problem.  Glad it's working now.
