### ISSUE TITLE
Show styling info from a syntax specific color scheme

### ISSUE THREAD

**Issue by aziz** [facelessuser/ScopeHunter#23]
I've enabled `{ "styling": true }` in my settings to see the foreground and background colors in ScopeHunter popup window. 
Here is my full user settings 

```json
{
  "show_popup": true,
  "show_panel": false,
  "styling": true,
  "show_simulated_alpha_colors": true,
  "selectors": true,
  "highlight_style": "outline",
  "extent_points": true
}
```

The bug is happening when you're looking a file (like a markdown file) that has syntax specific color scheme. The colors that are shown in styling section of scope hunter are from the default color scheme, not the current view's color scheme.

**Comment by facelessuser** [comment]
I believe I understand.  It's a case that I apparently overlooked. Shouldn't be too hard to address.  Thanks for the report.

**Comment by facelessuser** [comment]
Commit https://github.com/facelessuser/ScopeHunter/commit/7f9dccbf365e0581fab4d53e6c88a317eee14313 should fix it.  I want to do a little more testing, then I will do a bugfix release.  Probably expect it in the next couple of days.

**Comment by facelessuser** [comment]
Released in 2.0.1

**Comment by FichteFoll** [comment]
It should never be necessary to directly load settings from `Preferences.sublime-settings` because its values get virtualized into the view's settings object. You really only need to load the settings directly if you want to modify them.

**Comment by facelessuser** [comment]
I actually already realized this which is why the new tooltip lib used by ScopeHunter doesn't access Preferences, I just haven't updated ScopeHunter yet.  Basically the code to access Preferences will never get accessed because of what you said thereby essentially making the code dead.  It will get cleaned out eventually.
