### ISSUE TITLE
ScopeHunter fails if tmTheme file contains html comments

### ISSUE THREAD

**Issue by aziz** [facelessuser/ScopeHunter#24]
I just found that ScopeHunter and a plugin of mine both fail on a particular color scheme. 
After a little bit of investigation I realized it's because of the HTML comments inside the plist file. 
Although I think comments are not valid in plist files but people use them in the wild, so I fixed mine using this snippet. 

```python
file_content = sublime.load_resource(scheme_file)
removed_comments = re.sub(r"<!--.+-->", '', file_content)
plist_file = plistlib.readPlistFromBytes(bytes(removed_comments, 'UTF-8'))
```

Maybe you can do the same in ScopeHunter.

**Comment by facelessuser** [comment]
Comments don't always break plists (I have had comments in my themes before), but the builtin plist parser just seems to have problems with certain kinds.  One that makes perfect sense is like the one seen here https://github.com/facelessuser/ScopeHunter/issues/22#issuecomment-146980886; I've seen this issue more than once.

With all of that said, I get where you are coming from, and it probably isn't a bad idea to strip them out to be safe, but I think we would need to be a little more aggressive than what you posted above as that will not take care of multi-line comments which people are so fond of using.

Out of curiosity, what type of comment was it choking on?

**Comment by aziz** [comment]
You're right, we need to take care of multi line comments as well. 
Anyway, the parser chocked on a single line comment like here: 
https://github.com/aziz/SublimeFileBrowser/blob/master/dired.hidden-tmTheme#L172

**Comment by facelessuser** [comment]
> Anyway, the parser chocked on a single line comment like here: 
https://github.com/aziz/SublimeFileBrowser/blob/master/dired.hidden-tmTheme#L172
and here:
https://github.com/aziz/SublimeFileBrowser/blob/master/dired.hidden-tmTheme#L262

Cool, that is what I thought.  The plistlib that parses plists (which I guess uses xml.expat or something like that) chokes on `--` in comments.  Comments in general are fine, but it has a hard time with that for some reason.  I think the comment detection is kind of weak.

Regardless, it is probably time I just patch it and be done with it.

**Comment by aziz** [comment]
I wish `sublime.load_resource()` could have done that automatically. Sounds like a feature request.

**Comment by facelessuser** [comment]
> I wish sublime.load_resource() could have done that automatically. Sounds like a feature request.

Yeah, since clearly Sublime can handle the comments, it and it knows that `tmLanguage` is a sublime extension, it would be nice to have that automatically.

Probably going to go with something like this.  If someone uses comments at the start of the file, the encoding deceleration won't be first, so you have to eat up all the white space.  They shouldn't have comments as the first thing, but I just keep running into it.  This should handle multiline comments as well.

```python
            readPlistFromBytes(
                re.sub(
                    br"(\r?\n?\s*)*<!--[\s\S]*?-->(\s*\r?\n?)*", b'',
                    sublime.load_binary_resource(sublime_format_path(self.color_scheme))
                )
            )
```

**Comment by facelessuser** [comment]
commit https://github.com/facelessuser/ScopeHunter/commit/8d1b1c1d439f818615275e10013d1d0208c0bf80 should fix this moving forward.  I should hopefully have a bug fix release maybe by tonight.

**Comment by aziz** [comment]
:+1: great work.

**Comment by facelessuser** [comment]
FYI, regex was too inefficient and was causing a small subset of schemes hang a little when parsing, this has been corrected in https://github.com/facelessuser/ScopeHunter/commit/e14d2eeefbf60792149b73282d384a51345478a3.

**Comment by aziz** [comment]
Thanks for the heads up.

**Comment by FichteFoll** [comment]
Against popular belief, XML follows the SGML way of commenting, which is not `<!-- comment -->` but `-- comment --` within `<!` and `>`. Sounds weird, but is a notable difference. The problem now is that different parsers do different things. Some follow the SGML and some the ... idk, custom way maybe. I'm not sure how far the SGML spec actually reaches and which comment standard PList files have specified.

Anyhow, our line in question:
```
<!-- HELP ----------------------------- -->
```
has exactly 9 `-- --` comment pairs + a remaining `-` that seems to fit nowhere. From what I understand, this *should* be a valid comment either way. If we remove the definitive comment pairs, we get `<!--- -->`. So even after all this, I don't know why parsing it would fail.

Resources:
https://github.com/SublimeTextIssues/Core/issues/1018
http://stackoverflow.com/a/2757486/1327727
http://stackoverflow.com/a/12102131/1327727

**Comment by facelessuser** [comment]
Mine is not to question why,  just keep keep it from colossally failing :).
