### ISSUE TITLE
Put exception output when color scheme file does not exist under debug switch

### ISSUE THREAD

**Issue by FichteFoll** [facelessuser/ScopeHunter#27]
This is related to my InactivePanes package, which (at the moment) periodically clears its cache of generated color schemes, but can't remove all references to these files from other projects because there is no "on window close" event, so the view ends up with a pointer to a non-existant color scheme for a very short time. It's enough to generate several error messages from Sublime Text and cause the following exception however:

```
Traceback (most recent call last):
  File "scope_hunter in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\ScopeHunter.sublime-package", line 718, in init_color_scheme
  File "lib.color_scheme_matcher in C:\Users\Fichte\AppData\Roaming\Sublime Text 3\Installed Packages\ScopeHunter.sublime-package", line 71, in __init__
  File "C:\Program Files\Sublime Text 3\sublime.py", line 146, in load_binary_resource
    raise IOError("resource not found")
OSError: resource not found
```

What follows are two more exceptions that are caused by Python-internal traceback printing and the way SublimeText loads Python files from zip archives, but that is irrelevant.

**Comment by facelessuser** [comment]
I will have to look at the path ScopeHunter takes to get to the crash.   I think it only reloads the scheme when the scheme changes.   I guess I don't yet understand how we are getting to the crash,  but I will take a look.   Is there an easy way to replicate with inactive panes?

**Comment by FichteFoll** [comment]
I assume the basic procedure is as follows, although I didn't verify:

1. Create a project.
2. Open a file with a syntax-specific color scheme in that project and have it active.
3. Close the project (after saving ofc).
4. Assert that there is another project open and restart Sublime Text.
5. Open the previously created project.

**Comment by facelessuser** [comment]
After looking at the code, it looks like I am catching the exception, but I print the traceback just for info to the user so they can look in the console to see why maybe it failed to read their color scheme.  I feel this is reasonable.  If you don't want to see the error, I can but it under a debug switch, but it looks like I am handling it gracefully.  I imagine ScopeHunter still works even though you are seeing the error?

Are you seeing other issues beside the logging of this caught error?

Since the scheme can't be found, I can't read what I can't find.  The only other reasonable thing I can do is fall back to the global preference's color scheme.

Does that sound reasonable?

**Comment by facelessuser** [comment]
> I imagine ScopeHunter still works even though you are seeing the error?

I imagine it obviously fails here, but not crash so it no longer works again without reloading.

**Comment by FichteFoll** [comment]
>After looking at the code, it looks like I am catching the exception, but I print the traceback

Looking at the code too and considering the many (2 or 3) following exceptions about the reverse code lookup failing, that does seem to be the case. However, because SublimeText messes with the stored name, which `sublime_plugin.ZipLoader.load_module` stores when it invokes `compile` with some `"bla.py in path_to.sublime-package"` string (line 704 for reference), it clutters up the console with many lines. Thus, you would need to try this with the package in archived state to reproduce the *full* issue of this report.

> I imagine ScopeHunter still works even though you are seeing the error?

I didn't test it on that specific view and I rarely use it anyway, so I'd need to reproduce it again.

**Comment by facelessuser** [comment]
To be honest,  I think inactive panes needs to be more careful about how it cleans up.   It should set views to good schemes before deleting them. 

My approach is to ensure scopehunter is gracefully handling a bad situation.  I will move the error under a debug switch to not clutter the console. I will double check to make sure bad schemes at least fail gracefully.

I personally believe the onus is on InactivePanes.   It is creating this bad situation.   It should never leave a view with a bad scheme.   As long as scopehunter can recover,  I'm okay.

**Comment by FichteFoll** [comment]
> I personally believe the onus is on InactivePanes. It is creating this bad situation. It should never leave a view with a bad scheme.

Honestly, InactivePanes is just *triggering* the issue, but people could as well just set a view-specific or project-specific, or even syntax-specific color scheme and then delete the scheme (e.g. the package it resides in) while the project is not open. It will create the same symptoms.

That said,
> I think inactive panes needs to be more careful about how it cleans up.

I agree, and it's on my roadmap with plans to back it up. InactivePanes does have to clean-up files at some point because I don't want to cache them for all eternity, but it can definitely be less aggressive and more conservative with them.

>I will double check to make sure bad schemes at least fail gracefully.

Yes, this is all what I'm asking for here. It's definitely a low priority though.

---

I will report the console clogging with internal exceptions caused by Sublime Text externally.

**Comment by facelessuser** [comment]
Thanks, I think we are handling the failure fine, but I will double check.  I will definitely get some of the noise under a debug switch.  I can easily test a bad scheme even without inactive panes, so I should be able to knock this out tonight.

**Comment by facelessuser** [comment]
ScopeHunter is handling things fine, nothing needs to change.  I will but the message under a debug switch though.
