### ISSUE TITLE
hide window when plugin is toggled off

### ISSUE THREAD

**Issue by ctf0** [facelessuser/ScopeHunter#29]
when i call the plugin the first time it show up the console window which is good,
however when i try toggle off i have to use `Esc` to hide the console, 

is there away to hide the console once the plugin it toggled off instead of using the `Esc` key each time ?

**Comment by facelessuser** [comment]
What is it you were expecting it to do?   Esc is the common sublime dismissal action.

**Comment by ctf0** [comment]
i was expecting the window to dismiss by it self when i toggle the plugin off

**Comment by facelessuser** [comment]
> i toggle the plugin off

One, I am not sure what you mean by this.  Disable the plugin completely?  Turn off auto mode?

Second, I am not really sure what display method you are using.  With the Sublime console or popups, I can not be sure you haven't already closed them and are not showing a new popup or re-opened console.  There is no hide popup or console event that can be leveraged to track which instance was already closed.  There might be a way to construct an elaborate system to somehow track this, but I personally don't find it worth the effort at this point.  If you see a panel/popup you don't want to see anymore, just press escape.  It has always seemed reasonable to me.

I guess I am open to hearing a justification for such a feature and possible proposal on how you imagine we would target the exact popup or the exact console instance.  I could probably only reasonably target the output panel, but not the popup tooltips and general console instance.

**Comment by ctf0** [comment]
here is a ss to better illustrate what i mean, now when i chose that cmnd in the ss the window at the bottom should hide automatically.
 
![test](https://cloud.githubusercontent.com/assets/7388088/12386475/6ee77354-bdce-11e5-969e-f6558a1f830b.jpg)

**Comment by facelessuser** [comment]
I should be able to detect the normal output panel that you are showing, but this will not work for popup tooltips or the the console option as there is no way to detect if they are the instance opened by ScopeHunter, or instances opened for some other unrelated reason.  I won't bother closing a debug console.   I **might** auto close any tooltip moving forward if "show_popup" is enabled, but I have no way to detect that it is or is not a scopehunter tooltip at this time. 

Anyways, I may push a fix sometime soon if I have time.

**Comment by ctf0** [comment]
as scope hunter take over the console window anyway so we can just toggle it off if its open.

**Comment by facelessuser** [comment]
Output panel vs console is not the same.  I don't know if anyone even uses the console option; I have considered removing it.  But for debug purposes, I will never force close the console if already open (not that I can detect it being open anyways).

What you are showing me is not the console, but is the output panel which I can detect, know it is only related to ScopeHunter, and can successfully close.

As for the tooltip, it is probably not a big deal to dismiss those even though I cannot detect if it's ScopeHunter's or not.

**Comment by ctf0** [comment]
okay, thnx for the clarification
