### ISSUE TITLE
Don't run ScopeHunter, Windows XP SP3, Sublime Text 3

### ISSUE THREAD

**Issue by Kristinita** [facelessuser/ScopeHunter#30]
Occurs nothing when I direct the cursor at any objects.

![ScopeHunter Bad](https://i.gyazo.com/b4be68b7bb750a09640cec033644038a.png)

Log of installation:

```
reloading Packages/User/Preferences.sublime-settings
ignored packages updated to: ["ScopeHunter", "Vintage"]
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: The dependency python-markdown is not currently installed; installing
Package Control: The dependency python-markdown has successfully been installed or updated
Package Control: The dependency mdpopups is not currently installed; installing
Package Control: The dependency mdpopups has successfully been installed or updated
Package Control: The dependency python-jinja2 is not currently installed; installing
ignored packages updated to: ["0_package_control_loader", "ScopeHunter", "Vintage"]
unloading plugin 0_package_control_loader.00-package_control
unloading plugin 0_package_control_loader.01-pygments
unloading plugin 0_package_control_loader.02-bz2
unloading plugin 0_package_control_loader.50-backrefs
unloading plugin 0_package_control_loader.50-python-markdown
unloading plugin 0_package_control_loader.50-pyyaml
unloading plugin 0_package_control_loader.50-requests
unloading plugin 0_package_control_loader.51-python-jinja2
reloading Packages/User/Package Control.sublime-settings
Package Control: The dependency python-jinja2 has successfully been installed or updated
Package Control: The dependency markupsafe is not currently installed; installing
reloading Packages/User/Preferences.sublime-settings
Package Control: The dependency markupsafe has successfully been installed or updated
ignored packages updated to: ["ScopeHunter", "Vintage"]
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-python-jinja2
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
reloading Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin ScopeHunter.scope_hunter
reloading Packages/ScopeHunter/scope_hunter.sublime-settings
reloading plugin ScopeHunter.scope_hunter_notify
indexing [queue 8]: no files were indexed out of the 2 queued, abandoning crawl
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
indexing [queue 9]: no files were indexed out of the 2 queued, abandoning crawl
Unable to open /C/Documents and Settings/Admin.USER-AC59577756/Application Data/Sublime Text 3/Packages/ScopeHunter/scope_hunter.sublime-settings
```

and then there was the following message: 

`ScopeHunter: Theme parsing failed!  Ignoring theme related info.`

My color theme is Monokai. Thanks.

**Comment by facelessuser** [comment]
Did you restart Sublime after installation?  Some times when new packages are installed (especially when they have dependencies), a restart is needed to have the entire package load proper.

It is working for me with the default Monokai that is shipped with Sublime.  If you are using a variant on Monokai instead of the default, please direct me at it.

**Comment by Kristinita** [comment]
@facelessuser 

 > Did you restart Sublime after installation?

Yes, I several times restart Sublime Text 3.

> If you are using a variant on Monokai instead of the default, please direct me at it. 

I switched to some the most popular color themes, but ScopeHunter didn't earn never, and in the console the following mistake was always removed:

`ScopeHunter: Theme parsing failed!  Ignoring theme related info.`

Thanks.

**Comment by facelessuser** [comment]
- What version of Sublime Text 3?
- Do you have any plugins that auto-modify color schemes?
- Did you install ScopeHunter via Package Control or did you do it manually?

I have to be honest, right now it is sounding like there is something wrong with your environment.  I have tried ScopeHunter in OSX, Windows, and Linux and it is working in all of them on Sublime Text 3.

**Comment by facelessuser** [comment]
This is looking suspicious in your log:

```
Unable to open /C/Documents and Settings/Admin.USER-AC59577756/Application Data/Sublime Text 3/Packages/ScopeHunter/scope_hunter.sublime-settings
```

**Comment by facelessuser** [comment]
Okay, usually when Package Control installs a package (unless it is told to do otherwise) it installs the package as a zip file in `Sublime Text 3/Installed Packages`, but I see that you have ScopeHunter under `Sublime Text 3/Packages` unzipped (at least that is the way it looks in the log).  Is it possible you have two copies?  One in `Installed Packages`, and one in `Packages`?  If so, delete the one in `Packages` and restart.

**Comment by Kristinita** [comment]
> What version of Sublime Text 3?

Sublime Text 3, Build 3103.

> Do you have any plugins that auto-modify color schemes?

List of my plugins:
 
![List of my plugins](https://i.gyazo.com/081eb4161055e5d12b1945100e9f26e8.png)

I am not sure, but I think that among them isn't present such that «auto-modify color schemes».

> Did you install ScopeHunter via Package Control or did you do it manually?

I made installation using Package Control.

**Comment by facelessuser** [comment]
> I am not sure, but I think that among them isn't present such that «auto-modify color schemes».

Color Highlighter modifies color schemes to inject all the colors it shows via highlights.  But I just installed Color Highlighter and it seems to have no negative effects on ScopeHunter on my machines.  Nothing else stands out to me...

You are using the Sublime Text beta, while I am using the latest Sublime Text dev, so maybe there is something there.  I don't think there is anything significant in regards to ScopeHunter between the beta and dev, but I will verify it.  I won't be able to confirm until tomorrow.  This is probably the last thing I can check.  I'll let you know what I find as soon as I try it out.

**Comment by Kristinita** [comment]
@facelessuser 
 
> One in Installed Packages, and one in Packages? 

I didn't find that the copy of ScopeHunter was somewhere in the Packages folder.

![My folder «Packages»](https://i.gyazo.com/571ea27c2d66cc3197df40ae5e6d7c5b.png)

Only file **ScopeHunter.sublime-package** in `Installed Packages` folder.

**Comment by facelessuser** [comment]
Okay, that means Sublime displays messages about files as of they are in Packages even if they are not.  That's fine.

**Comment by facelessuser** [comment]
Unfortunately I haven't got around to testing this today yet, but I wanted to ask if you have tired uninstalling ScopeHunter and reinstalling?

I get this feeling that something is corrupted.  There are a number of people who use this plugin (many of which are probably still on the beta channel), and you are the first person I am seeing this issue from.  I am hoping to get to testing the beta tonight, but I figured I should ask about the reinstalling as I don't expect to see an issue after I complete the testing.

**Comment by facelessuser** [comment]
I just tried out the beta.  It is working for me in the beta as well.  I would uninstall the plugin and re-install.  If it still isn't working, the only other thing I can recommend is possibly disabling other plugins to see if they are some how interfering.  Last resort, you can try and revert sublime: https://www.sublimetext.com/docs/3/revert.html.  I can't specifically test XP, but I doubt that is the issue.  There appears to be no issues with the plugin as far as I can tell, but something is messed up on your specific system.

**Comment by Kristinita** [comment]
@facelessuser , perhaps it matters. When I tried to remove with ScopeHunter through Package Control, Sublime Text hang up, and I had to close exit Sublime Text 3, and then start Sublime Text 3.

Then I couldn't establish ScopeHunter through Package Control.

```
Traceback (most recent call last):
  File "package_control.package_installer in C:\Documents and Settings\Admin.USER-AC59577756\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 159, in on_done
  File "package_control.package_disabler in C:\Documents and Settings\Admin.USER-AC59577756\Application Data\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 74, in disable_packages
ImportError: No module named 'package_control'
```
I exit and start Sublime Text 3, I estabilished ScopeHunter:

```
Package Control: The package 0_package_control_loader is being re-enabled after a Package Control operation was interrupted
Package Control: The package ScopeHunter is being re-enabled after a Package Control operation was interrupted
ignored packages updated to: ["Vintage"]
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: No updated packages
ignored packages updated to: ["ScopeHunter", "Vintage"]
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
Package Control: The dependency python-markdown is not currently installed; installing
Package Control: The dependency python-markdown has successfully been installed or updated
Package Control: The dependency mdpopups is not currently installed; installing
Package Control: The dependency mdpopups has successfully been installed or updated
Package Control: The dependency python-jinja2 is not currently installed; installing
ignored packages updated to: ["0_package_control_loader", "ScopeHunter", "Vintage"]
unloading plugin 0_package_control_loader.00-package_control
unloading plugin 0_package_control_loader.01-pygments
unloading plugin 0_package_control_loader.02-bz2
unloading plugin 0_package_control_loader.50-backrefs
unloading plugin 0_package_control_loader.50-markupsafe
unloading plugin 0_package_control_loader.50-python-markdown
unloading plugin 0_package_control_loader.50-pyyaml
unloading plugin 0_package_control_loader.50-requests
unloading plugin 0_package_control_loader.51-python-jinja2
unloading plugin 0_package_control_loader.55-mdpopups
reloading Packages/User/Package Control.sublime-settings
Package Control: The dependency python-jinja2 has successfully been installed or updated
Package Control: The dependency markupsafe is not currently installed; installing
reloading Packages/User/Preferences.sublime-settings
Package Control: The dependency markupsafe has successfully been installed or updated
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
ignored packages updated to: ["ScopeHunter", "Vintage"]
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.50-requests
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Vintage"]
reloading plugin ScopeHunter.scope_hunter
ScopeHunter: Theme parsing failed!  Ignoring theme related info.
reloading Packages/ScopeHunter/scope_hunter.sublime-settings
reloading plugin ScopeHunter.scope_hunter_notify
indexing [queue 5]: no files were indexed out of the 6 queued, abandoning crawl
reloading Packages/User/Package Control.sublime-settings
reloading Packages/User/Preferences.sublime-settings
ScopeHunter: Theme parsing failed!  Ignoring theme related info.
indexing [queue 6]: no files were indexed out of the 6 queued, abandoning crawl
```

Exit and start ST3, but again:

`ScopeHunter: Theme parsing failed!  Ignoring theme related info.`

**Comment by facelessuser** [comment]
It's not normal for package control to fail like that.  That isn't scope hunters fault.  Something is corrupted in your setup.  I would try a clean Sublime install.  You can try the portable Sublime download.

**Comment by Kristinita** [comment]
I delete my Sublime Text 3 → install portable version for Windows on [official site](https://www.sublimetext.com/3) → unpacked .zip to `D:\Sublime Text 3` → install Package Control → exit and run Sublime Text 3 → install ScopeHunter → exit and run Sublime Text 3. But under the caret nothing appears

![Nothing appears ScopeHunter](https://i.gyazo.com/fbc6da179ec7ed5473c12da51595fa75.png)

**Comment by facelessuser** [comment]
Did you run the scopehunter command from the command pallette?

**Comment by Kristinita** [comment]
> Did you run the scopehunter command from the command pallette?

No. Can you advise how to do this?

**Comment by facelessuser** [comment]
Press <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>p</kbd> and begin typing the name of one the commands listed here: http://facelessuser.github.io/ScopeHunter/usage/#command-usage.  You can either get the scope under the cursor, or turn on instant scoping which will keep showing the the scope under the cursor every time you move the cursor.  If using instant scoping, just run the command again to turn it off.

**Comment by Kristinita** [comment]
Now I have everything works well.

![ScopeHunter CommandPalette](https://i.gyazo.com/55c2ee568255c0d0a311a91b6ec86460.png)

How can I disable ScopeHunter by default, including the plugin only when I need to change the color of the scopes?

**Comment by facelessuser** [comment]
It isn't enabled by default.  I usually bind to a shortcut the one shot command to show the scope under the cursor.   If I am doing some serious work with scopes, I enable instant scoping just for the duration of my investigation, and then toggle it off.  It is not meant to be turned on and left on.

**Comment by facelessuser** [comment]
Feel free to ask more questions, but this issue looks to have been addressed as things are now working for you.  I will consider this issue closed.
