### ISSUE TITLE
Activate it only for one file

### ISSUE THREAD

**Issue by LeonardoGentile** [facelessuser/ScopeHunter#31]
Hello,
thank you very much for this plugin, I use it very often to customize sublime themes.
I'm not sure if it is possible or not: can I activate the plugin only for a specific (current one) file?

USE CASE: I'm using the plugin to get the scope a specific file extensions, let's say a .sass file. I click around to toggle the popup or the console and copy the found scopes. Then I go over the `.tmTheme` file I want to customize using the found scopes. In here it is very annoying to have the scopeHunter activated, especially when finding a specific string. The popup or the console are always in the way. So is this possible?

Thanks

**Comment by facelessuser** [comment]
Not currently.  It would have to get added.

**Comment by LeonardoGentile** [comment]
Do you think it could be a useful use case or is it just me? :grin: 
I don't have a good knowledge of plugin development but If you point me where to look I could try to understand what to do

**Comment by facelessuser** [comment]
I've just been busy.  I think it is very useful.  I should have a command up shortly.

**Comment by facelessuser** [comment]
Done and released.

**Comment by LeonardoGentile** [comment]
AWESOME! 👍  💃
