### ISSUE TITLE
Unable to find ScopeHunter in Package Control 

### ISSUE THREAD

**Issue by helloworld** [facelessuser/ScopeHunter#36]
I am unable to find ScopeHunter in Package Control within Sublime Text. 

Other packages can be found normally, but ScopeHunter is no where to be found. 

When I do `Package Control: Install Package` and search for 

"Scope":
![image](https://cloud.githubusercontent.com/assets/3893054/21561248/3690caca-ce38-11e6-9461-32a83e01270a.png)

"ScopeHunter:"
![image](https://cloud.githubusercontent.com/assets/3893054/21561244/2c2dcd94-ce38-11e6-8252-5611b8f14956.png)

Any ideas on why this is happening, or how I can fix this and install ScopeHunter?

Thanks!

**Comment by facelessuser** [comment]
Sometimes when a package has too many tags this happens.  I'll have to remove some.

**Comment by facelessuser** [comment]
I cleared out an old release. It should pop back up on Package Control within an hour or two.
