### ISSUE TITLE
Feature request - On-the-fly editing of tmTheme file.

### ISSUE THREAD

**Issue by bfelder** [facelessuser/ScopeHunter#37]
@facelessuser First of all a big thank you for putting out so much awesome plugins for sublime like ScopeHunter, ColorSchemeEditor and RegReplace!

I am using ScopeHunter and ColorScheme editor in conjunction to edit thTheme files.

My workflow includes having opened both the respective tmTheme file and an example file for the respective language, covering as completely as possible all syntax elements/ scopes.

ScopeHunter presents me with a nice popup showing the respective scope, fore- and background color.

I can then use the scope string to find the respective portion in the tmTheme file to edit the color according to my wishes. (_I know ColorSchemeEditor can put me right at the scope defintion of the color scheme file. Yet, there appears to be a bug that makes using ColorSchemeEditor in that way impossible. Namely clicking into the tmTheme file will make the viewport jump to an entirely different location of that file. Editing is rendered impossible. This is worthy of an issue filing in itself. And even if it worked it still not the best imaginable solution._)

This process works but is very cumbersome.

The following would be a big improvement, allowing on-the-fly color adjustments of a scheme.

**Just allow picking colors right from ScopeHunter's popup. The user may either input a new hex color or optionally use a color picker. _The plugin then handles the modification of the tmTheme file all by itself._**

The modification of the theme file then automatically change the coloring of any affected file. Providing the user with instant feedback.

This would allow for the most easy way to adjust color schemes.

Many of the required function are already implemented other plugins of yours, like the parsing of the tmTheme file or a color picker in ColorHelper. They just need to be put together in a new way.

Of course there is ColorSchemeEditor and ColorHelper but none make it as easy to edit a color scheme.

**Comment by facelessuser** [comment]
First, are we talking about [ColorSchemeEditor](https://packagecontrol.io/packages/ColorSchemeEditor) or my [ColorSchemeEditor](https://github.com/facelessuser/ColorSchemeEditor)?

> *I know ColorSchemeEditor can put me right at the scope defintion of the color scheme file. Yet, there appears to be a bug that makes using ColorSchemeEditor in that way impossible. Namely clicking into the tmTheme file will make the viewport jump to an entirely different location of that file. Editing is rendered impossible. This is worthy of an issue filing in itself. And even if it worked it still not the best imaginable solution.*

This doesn't sound like my ColorSchemeEditor.  Maybe I'm not understanding.

> **Just allow picking colors right from ScopeHunter's popup. The user may either input a new hex color or optionally use a color picker. *The plugin then handles the modification of the tmTheme file all by itself.***

This would turn ScopeHunter into a Color Scheme Editor, but that is not something I think I want to do.

**Comment by bfelder** [comment]
@facelessuser Thanks four fast reply. Indeed I was not aware there are two ColorSchemeEditors. I think is a bad idea PackageControl allows such confusion at all.

Your ColorSchemeEditor however appears close to what I need to do!

Thanks for pointing out!

**Comment by facelessuser** [comment]
@bfelder Mine is not on PackageControl.  It's current iteration doesn't support `popupsCss` and `phantomCss`.

I'm working on a new release that will ditch bundling binaries and instead require you to install via pip the editor on your systems Python.  I am actively working on the editor itself, and once done, I will update the plugin.  This may or may not be what you are looking for, but if it is it's a work in progress, but it is getting close.  The actual editor that is used by my ColorSchemeEditor is found here: https://github.com/facelessuser/subclrschm.  It still has a couple things I am doing to it before release, but it can now be run in Python2.7 or Python3.4+.

I *might* release it on PackageControl when done, but it will require a name change as you pointed out.

**Comment by bfelder** [comment]
Thanks for pointing the difference out. I am looking forward to another great plugin by the facelessuser!
