### ISSUE TITLE
Support for `sublime-color-scheme` format (JSON)

### ISSUE THREAD

**Issue by aziz** [facelessuser/ScopeHunter#43]
I'm playing with the new `sublime-color-scheme` format, but unfortunately scope hunter can not parse it at all. 
I know it's experimental and you probably wanna wait a bit but I think this should be added some time in future

**Comment by facelessuser** [comment]
This isn't really following the template. It should handle the format in the latest. What version are you using? Can you post the file it can't parse?

**Comment by aziz** [comment]
Sorry for not following up the template.

## Support Info
- ST ver.: 3152
- Platform: osx
- Arch: x64
- Plugin ver.: 2.9.1
- Install via PC: True
- mdpopups ver.: 3.0.2
- markdown ver.: 2.6.9
- pygments ver.: 2.1a0
- jinja2 ver.: 2.8

The only error I get is during launch

```
ScopeHunter: Theme parsing failed!  Ignoring theme related info.
```

and here is my color-scheme file:
https://github.com/aziz/sublimeText3-Userfiles/blob/master/Test.sublime-color-scheme

**Comment by facelessuser** [comment]
Thanks, I'll take a look. It's a new feature, and very few are using the new format to its extents, so I imagine there are some corner cases that I hadn't caught yet.

**Comment by facelessuser** [comment]
What's with the preceding spaces in front of some colors? I'll have to check if I'm stripping white space...

**Comment by facelessuser** [comment]
blue_light looks empty. Looks like you're trying to stress test ScopeHunter :).

**Comment by aziz** [comment]
😄 Yes I've been a bit sloppy since it's just a test. but note that it still works in sublime, so it should be parsable by ScopeHunter as well.

**Comment by facelessuser** [comment]
No worries, this is the kind of testing I need :).

**Comment by aziz** [comment]
Removing preceding spacing and remove giving a temp value to `blue_light` fixed the issue. I'm happy if you close it. but it would be nice to add some guards against these mal-formatted cased.

**Comment by facelessuser** [comment]
Of course, guards are definitely needed. Some of those  didn't come over when I created support for the new format... Mainly because I put in minimal effort to get it working. All this hobby coding gets in the way of spending time with my family, so I don't always cross all of my `t`s so I can get back to more important things :). I expected *some* bugs when people started using it.

**Comment by facelessuser** [comment]
@aziz I'll have a fix out soon, but don't use `defaults` use `globals`.  Though Sublime currently parses both, `defaults` was introduced in 3151, but was changed to `globals` in 3152.  You'll notice even though sublime still parses `defaults` in 3152, the default popups are not finding back ground and foreground, this is with no plugins.  So use `globals`.

**Comment by aziz** [comment]
Thanks for the heads up. you're awesome.
