### ISSUE TITLE
ScopeHunter: Theme parsing failed!  Ignoring theme related info.

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/ScopeHunter#49]
Look like ScopeHunter can't yet cope with the new _*.sublime-theme_ format of ST3180+?

```JSON
{
    "name": "ayu",
    "author": "Ike Ku",
    "variables":
    {
        "black": "hsl(0, 0%, 0%)",
    },
    "globals":
    {
        "foreground": "var(orange6)",
        "background": "var(black3)",
    },
    "rules":
    [
    ]
}
```

**Comment by facelessuser** [comment]
What is it ignoring? Is it hsl? 

It should work if you use this branch: https://github.com/facelessuser/ScopeHunter/tree/new-scheme-support.

**Comment by facelessuser** [comment]
Hsl should have worked already, but I think there was a bug that got fixed on that branch. I think the main thing it doesn't support is foreground adjust. I've been consumed with other things and haven't gotten around to that. I should probably just release what I have and get to foreground adjust later.

**Comment by facelessuser** [comment]
I'll take a look at the example you've provided. I'll see if recent changes address these problems, and if so, I'll cut a release.

**Comment by facelessuser** [comment]
Also, you posted `*.sublime-theme`  I think you mean `*.sublime-color-scheme`? Also, why specifically 3180+, what was added in 3180 that isn't supported? I am aware of a few things that aren't supported, some that aren't currently used in may color schemes. 

You are going to have to provide a non-malformed scheme that fails. If it is malformed, currently it is expected to fail.

**Comment by facelessuser** [comment]
Also, this doesn't follow the template either. I would appreciate all future issues follow the template.

**Comment by deathaxe** [comment]
The example in the opening post is just an excerpt to indicate I am using the current color scheme style. It was converted with ST's convert color scheme function from the existing ayu-dark and is definitively very perfectly correct on my box. Just didn't want to bloat the post with all the details.

Dosn't matter, removed the plugin.

**Comment by facelessuser** [comment]
I don't think it is unreasonable to request to have a reproducible case. I'd love to get the issue fixed if you care to work with me to understand the issue.  I do not consider relevant info as bloat. If the official ayu-dark is the theme that was converted, I can take a look at that.  I just need details, not vague statements, with cryptic examples.

**Comment by facelessuser** [comment]
Running with ayu-dark, converted via Sublime (3184) (using hsl colors) and ScopeHunter version 2.11.1, I see no issues:

<img width="553" alt="ayu" src="https://user-images.githubusercontent.com/1055125/51130701-da136100-17ea-11e9-80db-3a4ebbc49326.png">

If more information is provided, I am happy to reopen this. A trace of what file is throwing this error, versions being used, full scheme that is failing, etc. Is the converted scheme being run, or did you convert it, but are still using the tmTheme in Sublime? Maybe a dependency like mdpopups was throwing the error (I may be running a different version there)?  If not, it seems ScopeHunter is handling it fine.
